---
networks:
  default:
    name: example.com

services:

  bastion:
    image: ansible-ssh-server
    container_name: bastion
    hostname: bastion
    privileged: true
    ports:
      - "5222:22"

  target:
    image: ansible-ssh-server
    privileged: true
