---
networks:
  default:
    name: example.com

# TIP: Use these services when testing indirect connection with bastion host
services:

  bastion:
    image: ansible-ssh-server
    container_name: bastion
    hostname: bastion
    privileged: true
    ports:
      - "5222:22"

  target:
    image: ansible-ssh-server
    privileged: true

# TIP: Use these service definitions when testing direct connection without bastion host
# services:

#   target:
#     image: ansible-ssh-server
#     privileged: true
#     ports:
#       - "22"